STABLECOIN_ADDRESSES = {
    "USDC": "0x3894085ef7ff0f0aedf52e2a2704928d1ec074f1",
}

# RPC Configuration
SEI_RPC_URL = "https://evm-rpc.sei-apis.com"
POLL_INTERVAL = 5
USDC_DECIMALS = 6
NETWORK = "sei"

WHALE_SINGLE_TX_THRESHOLD = 100.0
WHALE_VOLUME_THRESHOLD = 500000.0
WHALE_TIME_WINDOW_MINUTES = 60

BALANCE_CHECK_THRESHOLD = 100.0
BALANCE_MONITORING_ENABLED = True
BALANCE_CHECK_INTERVAL_BLOCKS = 5

# Event Bus Settings
EVENT_BUS_ENABLED = True
EVENT_BUS_AUTO_START = True
AI_ANALYSIS_ENABLED = False  # For Phase 1, will be enabled in Phase 2
EVENT_QUEUE_MAX_SIZE = 1000
EVENT_PROCESSING_TIMEOUT = 30

# SERVER_PARAMS = StdioServerParameters(
#     command="npx",
#     args=["-y", "@sei-js/mcp-server"],
#     env=None,
# )